### PR TITLE
Additional "Who is here" Commands: Fixes #1

### LINKED ISSUE #1: Feature Request: Additional "Who is here" Commands
Whose here
Anyone at the Space
Anyone at Denhac

### PR DESCRIPTION
**Pull request by oconnore**

### CODE REVIEW

**Comment by mike7seven** [comment]
Does this need pushed to production?

**Comment by MarkVaughn** [comment]
Yea the steps would be to Click the merge pull request and then on the pi git pull

**Comment by mike7seven** [comment]
Ok. I will push to the PI soon and update everyone.

**Comment by Jnesselr** [comment]
@mike7seven I see that this pull request is still open.

The only complaint I have about this is that the regex allows "anyone at the denhac". which I'm willing to call a feature. :)

**Comment by oconnore** [comment]
@Jnesselr also, the even more awesome query: "who at space"?

**Comment by mike7seven** [comment]
This is now in production.

**Pull request merged**
